/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

/**
 *
 * @author Ryzen 5
 */
public class AbrirCuenta extends javax.swing.JDialog {

    /**
     * Creates new form AbrirCuenta
     */
    public AbrirCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
    }
    
    public AbrirCuenta(java.awt.Frame parent, String title, boolean modal) {
        super(parent, title, modal);
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirCuentaPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        noCuentaLabel = new javax.swing.JLabel();
        cliente2Label = new javax.swing.JLabel();
        noCuenta2Label = new javax.swing.JLabel();
        abrirCuentaBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abrirCuentaPanel.setBackground(new java.awt.Color(70, 73, 75));
        abrirCuentaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(180, 180, 180));
        headerLabel.setText("Cuenta Nueva");
        abrirCuentaPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, 20));

        clienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clienteLabel.setForeground(new java.awt.Color(180, 180, 180));
        clienteLabel.setText("Cliente:");
        abrirCuentaPanel.add(clienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 80, 20));

        noCuentaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noCuentaLabel.setForeground(new java.awt.Color(180, 180, 180));
        noCuentaLabel.setText("Numero de cuenta:");
        abrirCuentaPanel.add(noCuentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, 20));

        cliente2Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 83, 85), 1, true));
        abrirCuentaPanel.add(cliente2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, 20));

        noCuenta2Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 83, 85), 1, true));
        abrirCuentaPanel.add(noCuenta2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 220, 20));

        abrirCuentaBtn.setBackground(new java.awt.Color(77, 79, 81));
        abrirCuentaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        abrirCuentaBtn.setForeground(new java.awt.Color(180, 180, 180));
        abrirCuentaBtn.setText("Abrir Cuenta");
        abrirCuentaBtn.setToolTipText("");
        abrirCuentaBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 102, 104), 2));
        abrirCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCuentaBtnActionPerformed(evt);
            }
        });
        abrirCuentaPanel.add(abrirCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 110, 30));

        regresarBtn.setBackground(new java.awt.Color(77, 79, 81));
        regresarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(180, 180, 180));
        regresarBtn.setText("Regresar");
        regresarBtn.setToolTipText("");
        regresarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 102, 104), 2));
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        abrirCuentaPanel.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 100, 30));

        jSeparator1.setBackground(new java.awt.Color(90, 92, 94));
        jSeparator1.setForeground(new java.awt.Color(120, 122, 124));
        abrirCuentaPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 103, 480, 20));

        getContentPane().add(abrirCuentaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCuentaBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_abrirCuentaBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbrirCuenta dialog = new AbrirCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirCuentaBtn;
    private javax.swing.JPanel abrirCuentaPanel;
    private javax.swing.JLabel cliente2Label;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel noCuenta2Label;
    private javax.swing.JLabel noCuentaLabel;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
