/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

/**
 *
 * @author Ryzen 5
 */
public class Deposito extends javax.swing.JDialog {

    /**
     * Creates new form AbrirCuenta
     */
    public Deposito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
    }
    
    public Deposito(java.awt.Frame parent, String title, boolean modal) {
        super(parent, title, modal);
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositoPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        cuentaLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        cuentaCbx = new javax.swing.JComboBox<>();
        montoTxtField = new javax.swing.JTextField();
        regresarBtn = new javax.swing.JButton();
        depositarBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depositoPanel.setBackground(new java.awt.Color(70, 73, 75));
        depositoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(180, 180, 180));
        headerLabel.setText("Deposito");
        depositoPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 30));

        cuentaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuentaLabel.setForeground(new java.awt.Color(180, 180, 180));
        cuentaLabel.setText("Cuenta a depositar:");
        depositoPanel.add(cuentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, 20));

        montoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        montoLabel.setForeground(new java.awt.Color(180, 180, 180));
        montoLabel.setText("Monto:");
        depositoPanel.add(montoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, 20));

        cuentaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5645001236", "Item 2", "Item 3", "Item 4" }));
        depositoPanel.add(cuentaCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, -1));
        depositoPanel.add(montoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 220, -1));

        regresarBtn.setBackground(new java.awt.Color(77, 79, 81));
        regresarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(180, 180, 180));
        regresarBtn.setText("Regresar");
        regresarBtn.setToolTipText("");
        regresarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 102, 104), 2));
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        depositoPanel.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 160, 30));

        depositarBtn.setBackground(new java.awt.Color(77, 79, 81));
        depositarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositarBtn.setForeground(new java.awt.Color(180, 180, 180));
        depositarBtn.setText("Realizar Deposito");
        depositarBtn.setToolTipText("");
        depositarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 102, 104), 2));
        depositarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarBtnActionPerformed(evt);
            }
        });
        depositoPanel.add(depositarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(90, 92, 94));
        jSeparator1.setForeground(new java.awt.Color(120, 122, 124));
        depositoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 103, 480, 20));

        getContentPane().add(depositoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depositarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_depositarBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Deposito dialog = new Deposito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cuentaCbx;
    private javax.swing.JLabel cuentaLabel;
    private javax.swing.JButton depositarBtn;
    private javax.swing.JPanel depositoPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JTextField montoTxtField;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
