/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Ryzen 5
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        tableHeaderLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        cuentasTableScrollPane = new javax.swing.JScrollPane();
        cuentasTable = new javax.swing.JTable();
        perInfoPanel = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        domicilioTxtArea = new javax.swing.JTextArea();
        fechaLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        transfBtn = new javax.swing.JButton();
        newCuentaBtn = new javax.swing.JButton();
        cancelCuentaBtn = new javax.swing.JButton();
        depositoBtn = new javax.swing.JButton();
        updateInfoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion Bancaria");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 0, 68)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Menu");
        menuPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 620, 130));

        tableHeaderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableHeaderLabel.setText("Cuentas");
        menuPanel.add(tableHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 70, 20));

        clienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clienteLabel.setText("Cliente");
        menuPanel.add(clienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 70, 20));

        cuentasTableScrollPane.setBorder(null);

        cuentasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Cuenta", "Saldo", "Abierta Desde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cuentasTable.setShowGrid(true);
        cuentasTable.getTableHeader().setReorderingAllowed(false);
        cuentasTableScrollPane.setViewportView(cuentasTable);
        if (cuentasTable.getColumnModel().getColumnCount() > 0) {
            cuentasTable.getColumnModel().getColumn(0).setResizable(false);
            cuentasTable.getColumnModel().getColumn(1).setResizable(false);
            cuentasTable.getColumnModel().getColumn(2).setResizable(false);
        }

        menuPanel.add(cuentasTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 300));

        perInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        domicilioTxtArea.setBackground(new java.awt.Color(60, 63, 65));
        domicilioTxtArea.setColumns(20);
        domicilioTxtArea.setRows(5);
        domicilioTxtArea.setText("\n");

        javax.swing.GroupLayout perInfoPanelLayout = new javax.swing.GroupLayout(perInfoPanel);
        perInfoPanel.setLayout(perInfoPanelLayout);
        perInfoPanelLayout.setHorizontalGroup(
            perInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(perInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(domicilioTxtArea)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        perInfoPanelLayout.setVerticalGroup(
            perInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(domicilioTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        menuPanel.add(perInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 290, 210));
        menuPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 203, 800, 10));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        menuPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 20, 260));

        transfBtn.setText("Transferencia");
        transfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfBtnActionPerformed(evt);
            }
        });
        menuPanel.add(transfBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 120, -1));

        newCuentaBtn.setText("Abrir Cuenta");
        newCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCuentaBtnActionPerformed(evt);
            }
        });
        menuPanel.add(newCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 120, -1));

        cancelCuentaBtn.setText("Cancelar Cuenta");
        cancelCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCuentaBtnActionPerformed(evt);
            }
        });
        menuPanel.add(cancelCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 120, -1));

        depositoBtn.setText("Deposito");
        depositoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoBtnActionPerformed(evt);
            }
        });
        menuPanel.add(depositoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 120, -1));

        updateInfoBtn.setBackground(new java.awt.Color(60, 63, 65));
        updateInfoBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateInfoBtn.setText("Editar informacion personal");
        updateInfoBtn.setBorder(null);
        updateInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoBtnActionPerformed(evt);
            }
        });
        menuPanel.add(updateInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transfBtnActionPerformed

    private void newCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCuentaBtnActionPerformed

    private void cancelCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelCuentaBtnActionPerformed

    private void depositoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoBtnActionPerformed

    private void updateInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelCuentaBtn;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JTable cuentasTable;
    private javax.swing.JScrollPane cuentasTableScrollPane;
    private javax.swing.JButton depositoBtn;
    private javax.swing.JTextArea domicilioTxtArea;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton newCuentaBtn;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel perInfoPanel;
    private javax.swing.JLabel tableHeaderLabel;
    private javax.swing.JButton transfBtn;
    private javax.swing.JButton updateInfoBtn;
    // End of variables declaration//GEN-END:variables
}
