/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

/**
 *
 * @author Ryzen 5
 */
public class Transferencia extends javax.swing.JDialog {

    /**
     * Creates new form AbrirCuenta
     */
    public Transferencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
    }
    
    public Transferencia(java.awt.Frame parent, String title, boolean modal) {
        super(parent, title, modal);
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferenciaPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        cuenta1Label = new javax.swing.JLabel();
        transferirBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cuenta2Label = new javax.swing.JLabel();
        cuenta1Cbx = new javax.swing.JComboBox<>();
        cuenta2TxtField = new javax.swing.JTextField();
        montoTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transferenciaPanel.setBackground(new java.awt.Color(70, 73, 75));
        transferenciaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(180, 180, 180));
        headerLabel.setText("Transferencia");
        transferenciaPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 260, 20));

        montoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        montoLabel.setForeground(new java.awt.Color(180, 180, 180));
        montoLabel.setText("Monto:");
        transferenciaPanel.add(montoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 170, 20));

        cuenta1Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuenta1Label.setForeground(new java.awt.Color(180, 180, 180));
        cuenta1Label.setText("Retirar de cuenta:");
        transferenciaPanel.add(cuenta1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, 20));

        transferirBtn.setBackground(new java.awt.Color(77, 79, 81));
        transferirBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferirBtn.setForeground(new java.awt.Color(180, 180, 180));
        transferirBtn.setText("Realizar Transferencia");
        transferirBtn.setToolTipText("");
        transferirBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 102, 104), 2));
        transferirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirBtnActionPerformed(evt);
            }
        });
        transferenciaPanel.add(transferirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 160, 30));

        regresarBtn.setBackground(new java.awt.Color(77, 79, 81));
        regresarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(180, 180, 180));
        regresarBtn.setText("Regresar");
        regresarBtn.setToolTipText("");
        regresarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 102, 104), 2));
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        transferenciaPanel.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(90, 92, 94));
        jSeparator1.setForeground(new java.awt.Color(120, 122, 124));
        transferenciaPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 103, 480, 20));

        cuenta2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuenta2Label.setForeground(new java.awt.Color(180, 180, 180));
        cuenta2Label.setText("Transferir a cuenta:");
        transferenciaPanel.add(cuenta2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, 20));

        cuenta1Cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5645001236", "Item 2", "Item 3", "Item 4" }));
        transferenciaPanel.add(cuenta1Cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, -1));
        transferenciaPanel.add(cuenta2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 220, -1));
        transferenciaPanel.add(montoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 220, -1));

        getContentPane().add(transferenciaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_transferirBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Transferencia dialog = new Transferencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cuenta1Cbx;
    private javax.swing.JLabel cuenta1Label;
    private javax.swing.JLabel cuenta2Label;
    private javax.swing.JTextField cuenta2TxtField;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JTextField montoTxtField;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JPanel transferenciaPanel;
    private javax.swing.JButton transferirBtn;
    // End of variables declaration//GEN-END:variables
}
